[pytest]
pythonpath = .
asyncio_mode = auto
asyncio_default_fixture_loop_scope = module
asyncio_default_test_loop_scope = module
python_files = test_*.py
addopts = --cov=app --cov-report=term-missing
